name: Deploy to Cloudflare Workers

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Install dependencies
              run: uv sync

            - name: Create wrangler.toml
              run: |
                cat << EOF > wrangler.toml
                name = "${{ vars.CF_WORKER_NAME }}"
                main = "src/worker.py"
                account_id = "${{ secrets.CF_ACCOUNT_ID }}"
                compatibility_date = "${{ vars.CF_COMPATIBILITY_DATE }}"
                compatibility_flags = [ "python_workers" ]
                send_metrics = false
                workers_dev = false
                preview_urls = false
                [assets]
                directory = "./public"
                binding = "ASSETS"
                [[kv_namespaces]]
                binding = "STREAM_DATA"
                id = "${{ secrets.CF_KV_ID }}"
                preview_id = "${{ secrets.CF_KV_PREVIEW_ID }}"
                [[durable_objects.bindings]]
                name = "TWITCH_EVENTSUB"
                class_name = "TwitchEventSub"
                [[migrations]]
                tag = "v1"
                new_sqlite_classes = ["TwitchEventSub"]
                [triggers]
                crons = ["*/5 * * * *"]
                [vars]
                TWITCH_CHANNEL_ID = "1223232545"
                YOUTUBE_CHANNEL_ID = "UCReoJ7JCK8aD1yyBtzyKsJw"
                YOUTUBE_PLAYLIST_ID = "PLVWeVxBh7q-Y"
                [observability]
                enabled = false
                head_sampling_rate = 1

                [observability.logs]
                enabled = true
                head_sampling_rate = 1
                persist = true
                invocation_logs = true

                [observability.traces]
                enabled = false
                persist = true
                head_sampling_rate = 1
                EOF
            - name: Deploy with Pywrangler
              run: uv run pywrangler deploy
              env:
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
