name: Deploy to Cloudflare Workers

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                node-version: '24.18.0'
                cache: 'npm'

            - name: Create wrangler.toml
              run: |
                cat << EOF > wrangler.toml
                name = "${{ vars.CF_WORKER_NAME }}"
                main = "src/worker.js"
                account_id = "${{ secrets.CF_ACCOUNT_ID }}"
                compatibility_date = "${{ vars.CF_COMPATIBILITY_DATE }}"
                send_metrics = false
                workers_dev = false
                preview_urls = false
                [assets]
                directory = "./public"
                binding = "ASSETS"
                [[kv_namespaces]]
                binding = "STREAM_DATA"
                id = "${{ secrets.CF_KV_ID }}"
                preview_id = "${{ secrets.CF_KV_PREVIEW_ID }}"
                [[durable_objects.bindings]]
                name = "TWITCH_EVENTSUB"
                class_name = "TwitchEventSub"
                [[migrations]]
                tag = "v1"
                new_sqlite_classes = ["TwitchEventSub"]
                [triggers]
                crons = ["*/5 * * * *"]
                [vars]
                TWITCH_CHANNEL_ID = "1223232545"
                EOF
            - name: Deploy with Wrangler
              uses: cloudflare/wrangler-action@v4
              env:
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CF_ACCOUNT_ID }}
                command: deploy
